### ISSUE TITLE
Problems with spark -submit.

### ISSUE THREAD

**Issue by gsumar** [banzaicloud/spark-metrics#11] opened 2018-05-04 10:41 UTC
Hello,

I got some problems running spark in cluster mode. (works OK in client mode)

I am getting the next error: 
```
18/05/04 09:52:23 ERROR MetricsSystem: Sink class com.banzaicloud.spark.metrics.sink.PrometheusSink cannot be instantiated
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1854)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:284)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: java.lang.ClassNotFoundException: com.banzaicloud.spark.metrics.sink.PrometheusSink
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:230)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:198)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:194)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:194)
	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:102)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:366)
	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:201)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:223)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:67)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:66)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
```

The spark submit is exactly the same that was provided in the readme.

```
--repositories https://raw.github.com/banzaicloud/spark-metrics/master/maven-repo/releases 
--packages com.banzaicloud:spark-metrics_2.11:2.2.1-1.0.0,io.dropwizard.metrics:metrics-core:3.1.2 
--jars /home/hadoop/avro-1.8.2.jar,/home/hadoop/simpleclient-0.0.23.jar,/home/hadoop/simpleclient_dropwizard-0.0.23.jar,/home/hadoop/simpleclient_pushgateway-0.0.23.jar
```

**Comment by kozmagabor** [comment] 2018-05-04 10:44
Can you please be more specific about the issue?

**Comment by gsumar** [comment] 2018-05-04 10:50
I also tried downloading the jars and changing the statement:

```
 --conf spark.metrics.conf=/home/hadoop/metrics.properties --jars /home/hadoop/avro-1.8.2.jar,/home/hadoop/simpleclient-0.0.23.jar,/home/hadoop/simpleclient_dropwizard-0.0.23.jar,/home/hadoop/simpleclient_pushgateway-0.0.23.jar,/home/hadoop/spark-metrics_2.11-2.2.1-1.0.0.jar
```

Same result

**Comment by gsumar** [comment] 2018-05-04 11:06
Solved!! 

It wasn't taking the dependencies at first because some kind of problems with the maven repo (unable to download the files), need to download the project of those dependencies and build the jars.

Once I have it done and copied to the master node, I added this configuration in order to have it working for executors (that is why I was getting that error).
--conf spark.executor.extraClassPath=/home/hadoop/*:

Thanks.

**Comment by bonifaido** [comment] 2018-05-04 13:48
Great to see it worked out finally! If you don't mind I will close this issue. Feel free to open up new issues in case of you see something misbehaving.

**Closed by bonifaido** 2018-05-04 13:48 UTC

**Comment by Davben93** [comment] 2022-03-02 21:40
Hi!
I am having the same problem here.
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1894)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:419)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:408)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
        at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:439)

I am submitted a simple spark job in client mode on a k8s cluster with two nodes 

This is the command I have launched

bin/spark-submit --master k8s://https://192.168.1.18:6443 --deploy-mode client --name example --class example.Example --conf spark.executor.instances=1 --conf spark.driver.extraClassPath=shuffle.jar --conf spark.kubernetes.namespace=default --conf spark.kubernetes.container.image=myImages/sparkimage:3.2.1 --conf spark.kubernetes.authenticate.caCertFile=kubernetes/ca.crt --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.file.upload.path=kubernetes --verbose shuffle.jar
