### ISSUE TITLE
Push dropwizard metrics error, PushGatewayWithTimestamp: text format parsing error in line 64: second HELP line for metric name "HiveExternalCatalog_fileCacheHits"

### ISSUE THREAD

**Issue by kangtiann** [banzaicloud/spark-metrics#43] opened 2019-11-11 09:26 UTC
**Describe the bug**

Spark version: 2.4.3
spark-metrics version: spark-metrics_2.11-2.3-2.1.1.jar

Error in spark master.log:

`PushGatewayWithTimestamp: text format parsing error in line 64: second HELP line for metric name "HiveExternalCatalog_fileCacheHits"`

Reason is: **pushfateway may not accept duplicate metrics.**

here is push request body (while logging with debug level)
```
# HELP HiveExternalCatalog_fileCacheHits Generated from Dropwizard metric import (metric=HiveExternalCatalog.fileCacheHits, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_fileCacheHits gauge
HiveExternalCatalog_fileCacheHits 0.0
# HELP HiveExternalCatalog_filesDiscovered Generated from Dropwizard metric import (metric=HiveExternalCatalog.filesDiscovered, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_filesDiscovered gauge
HiveExternalCatalog_filesDiscovered 0.0
# HELP HiveExternalCatalog_hiveClientCalls Generated from Dropwizard metric import (metric=HiveExternalCatalog.hiveClientCalls, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_hiveClientCalls gauge
HiveExternalCatalog_hiveClientCalls 0.0
# HELP HiveExternalCatalog_parallelListingJobCount Generated from Dropwizard metric import (metric=HiveExternalCatalog.parallelListingJobCount, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_parallelListingJobCount gauge
HiveExternalCatalog_parallelListingJobCount 0.0
# HELP HiveExternalCatalog_partitionsFetched Generated from Dropwizard metric import (metric=HiveExternalCatalog.partitionsFetched, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_partitionsFetched gauge
HiveExternalCatalog_partitionsFetched 0.0
# HELP CodeGenerator_compilationTime Generated from Dropwizard metric import (metric=CodeGenerator.compilationTime, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_compilationTime summary
CodeGenerator_compilationTime{quantile="0.5"} 0.0
CodeGenerator_compilationTime{quantile="0.75"} 0.0
CodeGenerator_compilationTime{quantile="0.95"} 0.0
CodeGenerator_compilationTime{quantile="0.98"} 0.0
CodeGenerator_compilationTime{quantile="0.99"} 0.0
CodeGenerator_compilationTime{quantile="0.999"} 0.0
CodeGenerator_compilationTime_count 0.0
# HELP CodeGenerator_generatedClassSize Generated from Dropwizard metric import (metric=CodeGenerator.generatedClassSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_generatedClassSize summary
CodeGenerator_generatedClassSize{quantile="0.5"} 0.0
CodeGenerator_generatedClassSize{quantile="0.75"} 0.0
CodeGenerator_generatedClassSize{quantile="0.95"} 0.0
CodeGenerator_generatedClassSize{quantile="0.98"} 0.0
CodeGenerator_generatedClassSize{quantile="0.99"} 0.0
CodeGenerator_generatedClassSize{quantile="0.999"} 0.0
CodeGenerator_generatedClassSize_count 0.0
# HELP CodeGenerator_generatedMethodSize Generated from Dropwizard metric import (metric=CodeGenerator.generatedMethodSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_generatedMethodSize summary
CodeGenerator_generatedMethodSize{quantile="0.5"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.75"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.95"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.98"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.99"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.999"} 0.0
CodeGenerator_generatedMethodSize_count 0.0
# HELP CodeGenerator_sourceCodeSize Generated from Dropwizard metric import (metric=CodeGenerator.sourceCodeSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_sourceCodeSize summary
CodeGenerator_sourceCodeSize{quantile="0.5"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.75"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.95"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.98"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.99"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.999"} 0.0
CodeGenerator_sourceCodeSize_count 0.0
# HELP master_aliveWorkers Generated from Dropwizard metric import (metric=master.aliveWorkers, type=org.apache.spark.deploy.master.MasterSource$$anon$2)
# TYPE master_aliveWorkers gauge
master_aliveWorkers 1.0
# HELP master_apps Generated from Dropwizard metric import (metric=master.apps, type=org.apache.spark.deploy.master.MasterSource$$anon$3)
# TYPE master_apps gauge
master_apps 0.0
# HELP master_waitingApps Generated from Dropwizard metric import (metric=master.waitingApps, type=org.apache.spark.deploy.master.MasterSource$$anon$4)
# TYPE master_waitingApps gauge
master_waitingApps 0.0
# HELP master_workers Generated from Dropwizard metric import (metric=master.workers, type=org.apache.spark.deploy.master.MasterSource$$anon$1)
# TYPE master_workers gauge
master_workers 1.0
# HELP HiveExternalCatalog_fileCacheHits Generated from Dropwizard metric import (metric=HiveExternalCatalog.fileCacheHits, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_fileCacheHits gauge
HiveExternalCatalog_fileCacheHits 0.0
# HELP HiveExternalCatalog_filesDiscovered Generated from Dropwizard metric import (metric=HiveExternalCatalog.filesDiscovered, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_filesDiscovered gauge
HiveExternalCatalog_filesDiscovered 0.0
# HELP HiveExternalCatalog_hiveClientCalls Generated from Dropwizard metric import (metric=HiveExternalCatalog.hiveClientCalls, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_hiveClientCalls gauge
HiveExternalCatalog_hiveClientCalls 0.0
# HELP HiveExternalCatalog_parallelListingJobCount Generated from Dropwizard metric import (metric=HiveExternalCatalog.parallelListingJobCount, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_parallelListingJobCount gauge
HiveExternalCatalog_parallelListingJobCount 0.0
# HELP HiveExternalCatalog_partitionsFetched Generated from Dropwizard metric import (metric=HiveExternalCatalog.partitionsFetched, type=com.codahale.metrics.Counter)
# TYPE HiveExternalCatalog_partitionsFetched gauge
HiveExternalCatalog_partitionsFetched 0.0
# HELP CodeGenerator_compilationTime Generated from Dropwizard metric import (metric=CodeGenerator.compilationTime, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_compilationTime summary
CodeGenerator_compilationTime{quantile="0.5"} 0.0
CodeGenerator_compilationTime{quantile="0.75"} 0.0
CodeGenerator_compilationTime{quantile="0.95"} 0.0
CodeGenerator_compilationTime{quantile="0.98"} 0.0
CodeGenerator_compilationTime{quantile="0.99"} 0.0
CodeGenerator_compilationTime{quantile="0.999"} 0.0
CodeGenerator_compilationTime_count 0.0
# HELP CodeGenerator_generatedClassSize Generated from Dropwizard metric import (metric=CodeGenerator.generatedClassSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_generatedClassSize summary
CodeGenerator_generatedClassSize{quantile="0.5"} 0.0
CodeGenerator_generatedClassSize{quantile="0.75"} 0.0
CodeGenerator_generatedClassSize{quantile="0.95"} 0.0
CodeGenerator_generatedClassSize{quantile="0.98"} 0.0
CodeGenerator_generatedClassSize{quantile="0.99"} 0.0
CodeGenerator_generatedClassSize{quantile="0.999"} 0.0
CodeGenerator_generatedClassSize_count 0.0
# HELP CodeGenerator_generatedMethodSize Generated from Dropwizard metric import (metric=CodeGenerator.generatedMethodSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_generatedMethodSize summary
CodeGenerator_generatedMethodSize{quantile="0.5"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.75"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.95"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.98"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.99"} 0.0
CodeGenerator_generatedMethodSize{quantile="0.999"} 0.0
CodeGenerator_generatedMethodSize_count 0.0
# HELP CodeGenerator_sourceCodeSize Generated from Dropwizard metric import (metric=CodeGenerator.sourceCodeSize, type=com.codahale.metrics.Histogram)
# TYPE CodeGenerator_sourceCodeSize summary
CodeGenerator_sourceCodeSize{quantile="0.5"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.75"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.95"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.98"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.99"} 0.0
CodeGenerator_sourceCodeSize{quantile="0.999"} 0.0
CodeGenerator_sourceCodeSize_count 0.0

```

**Steps to reproduce the issue:**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/39302402/68575868-f8e49180-04a7-11ea-849b-d270b26ab494.png)

**Additional context**

**Comment by kangtiann** [comment] 2019-11-11 09:28
I will commit PR to fix this.

**Comment by stoader** [comment] 2019-11-11 09:57
That's a warning from Prometheus Pushgatway which doesn't accept two metrics instances that have the same keys but the different help message. This is to do with how the DropWizzard Prometheus exporter generates help messages for metrics. In the latest version, this should not happen as the help string is set to a fixed message now https://github.com/banzaicloud/spark-metrics/blob/master/src/main/scala/com/banzaicloud/spark/metrics/DropwizardExports.scala#L32 thus two instances of the same metric won't have different help message strings. Are you sure that you're running the latest version.

**Comment by kangtiann** [comment] 2019-11-11 13:06
I build from master.

![image](https://user-images.githubusercontent.com/39302402/68589530-107f4280-04c7-11ea-84f5-fd287829eed3.png)

**Comment by kangtiann** [comment] 2019-11-11 13:17
https://github.com/prometheus/pushgateway/blob/master/vendor/github.com/prometheus/common/expfmt/text_parse.go

The second help comment may be error.

![image](https://user-images.githubusercontent.com/39302402/68590048-89cb6500-04c8-11ea-8f1e-f8365fe1e421.png)

**Comment by stoader** [comment] 2019-11-11 16:21
Can you check if the correct jar (you built from master branch) is picked up by your Spark deployment and not an older cached version? In the latest version as I mentioned before the HELP string fixed to `Generated from Dropwizard metric import`. Help strings like the ones in your log `HiveExternalCatalog_fileCacheHits Generated from Dropwizard metric import (metric=HiveExternalCatalog.fileCacheHits, type=com.codahale.metrics.Counter)` were generated by an earlier version of the jar.

**Comment by kangtiann** [comment] 2019-11-12 02:05
## Why help message not fixed to `Generated from Dropwizard metric import`?

I think class `DropwizardExports` import from wrong path.

![image](https://user-images.githubusercontent.com/39302402/68635383-4e19b500-0533-11ea-9984-98c654fe5a82.png)

After, still not work...

![image](https://user-images.githubusercontent.com/39302402/68635312-1f034380-0533-11ea-975e-72a95fea82fe.png)

![image](https://user-images.githubusercontent.com/39302402/68635469-9a64f500-0533-11ea-8bf1-f07c078705dc.png)

I think should remove duplicate metric like this:

![image](https://user-images.githubusercontent.com/39302402/68635572-f760ab00-0533-11ea-9561-9cdef477e0df.png)

**Comment by stoader** [comment] 2019-11-12 09:50
I pushed a fix, can you take the latest master an try again?

**Comment by kangtiann** [comment] 2019-11-12 11:58
Still not work, version of my pushgateway is v1.0.0

![image](https://user-images.githubusercontent.com/39302402/68669886-98785180-0586-11ea-956d-fc868f618b01.png)

![image](https://user-images.githubusercontent.com/39302402/68669963-bba30100-0586-11ea-8ff6-78eb92b85dfa.png)

**Comment by stoader** [comment] 2019-11-12 15:18
Can you check code snippet in your version of spark-metrics at PrometheusSink.scala:237 ?

**Comment by kangtiann** [comment] 2019-11-13 07:29
![image](https://user-images.githubusercontent.com/39302402/68742120-51dc3300-062a-11ea-9682-6a751aaf766e.png)

**Comment by kangtiann** [comment] 2019-11-13 07:30
Help message is ok now, but still not work.

**Comment by stoader** [comment] 2019-11-13 07:44
What error do you see now?

**Comment by kangtiann** [comment] 2019-11-14 13:09
Error same to early
If remove  duplicate metrics, everything is okey~

![image](https://user-images.githubusercontent.com/39302402/68859723-d9a56880-0722-11ea-86d4-e0f51f9d1c43.png)

**Comment by stoader** [comment] 2019-11-14 13:20
Can you describe the steps to reproduce the error so as we can repro it on our dev environment?

**Comment by kangtiann** [comment] 2019-11-15 07:28
Here is my docker compose: [prometheus-docker.zip](https://github.com/banzaicloud/spark-metrics/files/3850239/prometheus-docker.zip)

STEP 1: Start prometheus and pushgateway

`docker-compuse up`

STEP 2: spark 2.4.4, edit `metrics.properties`

```
# Enable Prometheus for all instances by class name
*.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink
# Prometheus pushgateway address
*.sink.prometheus.pushgateway-address-protocol=http
*.sink.prometheus.pushgateway-address=127.0.0.1:9091
*.sink.prometheus.period=10
*.sink.prometheus.unit=seconds
*.sink.prometheus.pushgateway-enable-timestamp=false
## Metrics name processing (version 2.3-1.1.0 +)
#*.sink.prometheus.metrics-name-capture-regex=<regular expression to capture sections metric name sections to be replaces>
#*.sink.prometheus.metrics-name-replacement=<replacement captured sections to be replaced with>
#*.sink.prometheus.labels=<labels in label=value format separated by comma>
# Support for JMX Collector (version 2.3-2.0.0 +)
*.sink.prometheus.enable-dropwizard-collector=true
*.sink.prometheus.enable-jmx-collector=false
#*.sink.prometheus.jmx-collector-config=/opt/spark/conf/monitoring/jmxCollector.yaml

# Enable HostName in Instance instead of Appid (Default value is false i.e. instance=${appid})
#*.sink.prometheus.enable-hostname-in-instance=true

# Enable JVM metrics source for all instances by class name
#*.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink
#*.source.jvm.class=org.apache.spark.metrics.source.JvmSource
```

STEP 3: copy `spark-metrics` dependence jars to spark's jar path

STEP 4: Start spark with standalone mode.

```bash
./sbin/start-master.sh
./sbin/start-slave.sh spark://XXXXXXXXX:7077
```

**Comment by stoader** [comment] 2019-11-16 15:31
@kangtiann I couldn't reproduce this issue.

I downloaded the spark-metrics jar and it's dependencied using `mvn dependency:get -DgroupId=com.banzaicloud -DartifactId=spark-metrics_2.11 -Dversion=2.3-2.1.2` command.

Then I copied the downloaded jars to spark's jar path `cp  ~/.m2/repository/com/banzaicloud/spark-metrics_2.11/2.3-2.1.2/spark-metrics_2.11-2.3-2.1.2.jar ssembly/target/scala-2.11/jars/`

Also, I used the metrics.properties that you just provided above.

Can you create a docker-compose that also start spar-master and spark-slave with the jars yu use included where this issue is reproducible?

**Comment by kangtiann** [comment] 2019-11-18 12:44
Here is docker compose contains spark and spark-metrics jars (only spark master) [prometheus-docker.zip](https://github.com/banzaicloud/spark-metrics/files/3858630/prometheus-docker.zip)

### Spark docker file

![image](https://user-images.githubusercontent.com/39302402/69053180-cc9ab900-0a43-11ea-9564-eead53eac078.png)

### Error message

![image](https://user-images.githubusercontent.com/39302402/69052996-63b34100-0a43-11ea-8558-5f942cc93959.png)

**Comment by stoader** [comment] 2019-11-21 15:47
Can re-try with the latest master?

Note you need to compile spark-metrics with `sbt ++2.11.12  package` for Scala 2.11 (your docker-compose setup uses Scala 2.11).

Also, the package of the Sink has changed thus use `*.sink.prometheus.class=org.apache.spark.banzaicloud.metrics.sink.PrometheusSink` in your metrics.properties

**Closed** 2019-12-23 08:17 UTC
